### ISSUE TITLE
Launcher breaking bug (TypeError, main_screen.py)

### ISSUE THREAD

**Issue by shir0tetsuo** [clockworkpi/launcher#329]
from **/tmp/x.log:**
```
Traceback (most recent call last):
  File "run.py", line 672, in <module>
    big_loop(config.GlobalCanvas)
  File "run.py", line 603, in big_loop
    main_screen.ReadTheDirIntoPages("/home/cpi/apps/Menu",1,main_screen._Pages[ len(main_screen._Pages) -1])
  File "/home/cpi/launcher/sys.py/UI/main_screen.py", line 571, in ReadTheDirIntoPages
    self.ReadTheDirIntoPages(_dir+"/"+i,pglevel+1,iconitem._LinkPage)
  File "/home/cpi/launcher/sys.py/UI/main_screen.py", line 571, in ReadTheDirIntoPages
    self.ReadTheDirIntoPages(_dir+"/"+i,pglevel+1,iconitem._LinkPage)
  File "/home/cpi/launcher/sys.py/UI/main_screen.py", line 583, in ReadTheDirIntoPages
    if FileExists( MySkinManager.GiveIcon( _dir+"/"+ReplaceSuffix(i2,"png"))):
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Please advise on a solution, after the first `Loading` and a few seconds in black screen, the launcher won't boot up and it gets stuck on Loading endlessly. After some configuration I've been frustratingly met with this error the past 2 days and trying to figure out why.

**Comment by cuu** [comment]
sorry for late reply

`_dir+"/"+ReplaceSuffix(i2,"png")`

I think the i2 does not have "png" included
that is why it is a NoneType because ReplaceSuffix return None


I guess the problem is fixed now , right ?
